### ISSUE TITLE
New triggers for precise control of daily price peaks

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.heatingcontroller#1]
It would be nice if you could create two new triggers that looked like this:

**Current price is [x] percent above todays average 
Current price is [x] percent below todays average**

where today is the average of all 24 hours of the _current_ day. That would make the triggers precise and perfect to cut the (usually) two price peaks every day. It would be great if you could add that functionality. Thanks! :-)

**Comment by balmli** [comment]
Thanks for the feedback.

I will look into that.

**Comment by balmli** [comment]
I have added two new conditions:

- 'Current price is [x] percent below today's average'
- 'Current price is [x] percent above today's average'

Can use the 'Utility price changed' as the trigger.

Just waiting for Athom to approve the update.

**Comment by TheArcturian** [comment]
That was really fast and good news. Thanks! 
Keep up your great job, Bjørnar!

**Comment by balmli** [comment]
V. 0.8.0 in app store now.
