### ISSUE TITLE
Conflicting Conditions for Prices

### ISSUE THREAD

**Issue by bwa** [balmli/no.almli.heatingcontroller#12]
Have two flows, one for finding the low proces of the day and one for the high prices of day, but both fires ...
![image](https://user-images.githubusercontent.com/170977/147418821-08fa81f3-7b10-4971-9a29-0ab40548fef4.png)
![image](https://user-images.githubusercontent.com/170977/147418826-7daab604-d157-4fe0-81c0-03e176805ba6.png)

The timeline shows that both fires at same hour. May I have misunderstood how this works ?
![image](https://user-images.githubusercontent.com/170977/147418859-73410c29-5bf5-48ec-a7cf-8ed058134b83.png)

**Comment by balmli** [comment]
Yes, as designed.  See here: https://community.homey.app/t/app-pro-heating-controller-with-utility-prices/7795

Rules for the high prices trigger:

- Only hours where ‘ECO mode’ is enabled are controlled
- The selected number of hours with the highest prices are found
- If there are two consecutive hours with high prices the second hour is skipped, to avoid having heaters turned off too long, or having thermostat temperatures to low too long
