### ISSUE TITLE
Beginner guide ?

### ISSUE THREAD

**Issue by bwa** [balmli/no.almli.heatingcontroller#3]
As a Homey Beginner, it's very hard to find the way to actually make this work. I suspect I miss some ground understanding, men have noe clue hos to actually make this constroller work. maybe a beginners guide ?

**Comment by balmli** [comment]
I guess you have already read the main page of the github repo: https://github.com/balmli/no.almli.heatingcontroller ?

Here's a summary:

To install:

1. install the device
2. Go to Advanced settings and adjust the schedule (if needed)
3. select price area and currency.
4. select country for holidays

Then add at least two flows for setting the temperatures for your thermostat based on "comfort" or "eco"..

Here is some examples for  flows:

https://balmli.github.io/no.almli.heatingcontroller/

**Comment by bwa** [comment]
Understand more now after a few weeks of Homey use (both good and bad experiences) Have tried Homey Heating Scheduler (HHS). My need is different zones with different schedules and different temperatures, looks like this solutions is more about a globals scheme with different temeratures. But HHS seems to not be 100% robust. 

But the control of waterheater bsed on energy prizes, seems to be more robus and smartert, so I will try to explore this more.

**Comment by balmli** [comment]
You can create as many Heating Controller devices as you want, with different schedules
