### ISSUE TITLE
00.00 hour update is not working

### ISSUE THREAD

**Issue by pelti51** [balmli/no.almli.heatingcontroller#4]
Hi

The 00.00 hour update is not working. The prize is not uopdated and the triggers are not working. The prive zone I hae is FI.

**Comment by Janno-A** [comment]
Hi 
The same for Estonian part (the time zone is the same GMT+2). When I compare with the stock data, then the other values between 01.00 and 23.00 are reported properly.

**Comment by balmli** [comment]
OK, thanks for reporting this.

I will try to fix this issue.

**Comment by oh2th** [comment]
Also in Finland (TZ=EET) and missing the price for 00.00 hour.

**Comment by balmli** [comment]
Should be fixed in v. 1.5.0.

https://homey.app/a/no.almli.heatingcontroller/test/

Please test.
